name: CI

on:
  push:
    branches:
      - main
      - '*-stable'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile:
          - Gemfile
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    name: "Tests: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}"
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Deletes Gemfile.lock
        run: rm Gemfile.lock
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bin/rake test
  loading-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gemfile:
          - Gemfile
        ruby:
          - "3.1"
          - "3.2"
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    name: "Loading Tests: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}"
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Delete Gemfile.lock
        run: rm Gemfile.lock
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bin/rake test:loading
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          bundler-cache: true
      - name: Run style checks
        run: bin/rubocop
  static_type_checking:
    runs-on: ubuntu-latest
    name: Type Checking
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          bundler-cache: true
      - name: Run static type checks
        run: bin/srb tc
  buildall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: [lint, tests, static_type_checking]
    steps:
      - name: Check build matrix status
        if: ${{ needs.tests.result != 'success' || needs.lint.result != 'success' || needs.static_type_checking.result != 'success' }}
        run: exit 1
